export const REQUEST_DATA = "REQUEST_DATA";
export const RECEIVE_DATA = "RECEIVE_DATA";

export const RECEIVE_SITE_PAGES = "RECEIVE_SITE_PAGES";
export const RECEIVE_SITE_PAGE = "RECEIVE_SITE_PAGE";

export const EDIT_SITE_PAGE = "EDIT_SITE_PAGE";
export const CREATE_SITE_PAGE = "CREATE_SITE_PAGE";